### ISSUE TITLE
error in kickstart

### ISSUE THREAD

**Issue by unnisa94** [rembik/ansible-role-kickstart-iso#2]
hi ,

![image](https://user-images.githubusercontent.com/55035265/64480509-b9b76d00-d1e6-11e9-8429-c1f43d483acd.png)

getting error. can please suggest how to resolve this error as I'm beginner in this.

**Comment by rembik** [comment]
Do you still have problems to run the role?
If so, please use this [issue template](http://github.com/rembik/ansible-role-kickstart-iso/issues/new/choose) and follow the instructions to create a detailed bug report.
